Unit 2/07-auth-and-oauth/05-oauth/Solution/project/users/models.py
from project import db, bcrypt, twitter_blueprint
from flask_login import UserMixin, current_user
from flask_dance.consumer.backend.sqla import OAuthConsumerMixin, SQLAlchemyBackend


class User(db.Model, UserMixin):

    __tablename__ = "users"

    # Columns in table
    id = db.Column(db.Integer, primary_key=True)
    # 50 characters is a sensible default for the max length of first/last names
    first_name = db.Column(db.String(50))
    last_name = db.Column(db.String(50))
    # 256 characters is a sensible default for the max length of emails/usernames
    username = db.Column(db.String(256), unique=True)
    password = db.Column(db.Text)
    messages = db.relationship('Message', backref='user', lazy='dynamic')

    def __init__(self, first_name=None, last_name=None, username=None, password=None):
        self.first_name = first_name
        self.last_name = last_name
        self.username = username
        self.password = bcrypt.generate_password_hash(password).decode('UTF-8')

    # Call the class method with User.authenticate()
    @classmethod
    # Method requires username and password
    def authenticate(cls, username, password):
        found_user = cls.query.filter_by(username=username).first()
        if found_user:
            authenticated_user = bcrypt.check_password_hash(
                found_user.password, password)
            if authenticated_user:
                # Return the user so we can log them in by storing information in the session
                return found_user
        return False

    # Set a custom string representation of user objects
    def __repr__(self):
        return f"User {self.first_name} {self.last_name}"


class OAuth(OAuthConsumerMixin, db.Model):
    # Maximum length of Twitter username is 15 characters
    twitter_username = db.Column(db.String(15), unique=True)
    user_id = db.Column(db.Integer, db.ForeignKey(User.id))
    user = db.relationship(User)


twitter_blueprint.backend = SQLAlchemyBackend(
    OAuth, db.session, user=current_user, user_required=False)

Unit 2/07-auth-and-oauth/05-oauth/Solution/project/users/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, validators


class UserForm(FlaskForm):
    first_name = StringField(
        'First Name', [validators.DataRequired(), validators.Length(min=1, max=50)])
    last_name = StringField(
        'Last Name', [validators.DataRequired(), validators.Length(min=1, max=50)])
    username = StringField('Username', validators=[
                           validators.DataRequired(), validators.Length(min=1, max=256)])
    password = PasswordField('Password', validators=[
                             validators.DataRequired()])


class LoginForm(FlaskForm):
    username = StringField('Username', validators=[
                           validators.DataRequired(), validators.Length(min=1, max=256)])
    password = PasswordField('Password', validators=[
                             validators.DataRequired()])


class DeleteForm(FlaskForm):
    pass

Unit 2/07-auth-and-oauth/05-oauth/Solution/project/users/views.py
from flask import Blueprint, render_template, url_for, request, redirect, flash, session

from project import db, app, bcrypt, twitter_blueprint
from project.users.forms import UserForm, LoginForm, DeleteForm
from project.users.models import User, OAuth
from project.helpers import not_loggedin_required, current_user_required

from flask_login import login_required, login_user, logout_user, current_user
from flask_dance.consumer import oauth_authorized
from sqlalchemy.orm.exc import NoResultFound
from sqlalchemy.exc import IntegrityError

users_blueprint = Blueprint('users', __name__, template_folder='templates')


# OAuth

@oauth_authorized.connect_via(twitter_blueprint)
def twitter_logged_in(twitter_blueprint, token):
    if not token:
        flash("Failed to log in with Twitter.", category="error")
        return False

    resp = twitter_blueprint.session.get("account/settings.json")

    if not resp.ok:
        msg = "Failed to fetch user info from Twitter."
        flash(msg, category="error")
        return False

    twitter_info = resp.json()
    twitter_username = twitter_info['screen_name']

    # Find this OAuth token in the database, or create it
    query = OAuth.query.filter_by(
        provider=twitter_blueprint.name,
        twitter_username=twitter_username,
    )
    try:
        # Existing OAuth token in database
        oauth = query.one()
    except NoResultFound:
        # Create new OAuth token
        oauth = OAuth(
            provider=twitter_blueprint.name,
            twitter_username=twitter_username,
            token=token,
        )

    # If the token is associated with a user (?), log the user in
    if oauth.user:
        login_user(oauth.user)
        flash("Successfully signed in with Twitter.")
    else:
        """
        # Successful OAuth authentication without adding OAuth to existing non-OAuth accounts
        # Create a new local user account for this user
        user = User(
            first_name=twitter_username,
            # Less secure, but no username is generated, so on its own password cannot be used to log in
            password='password' 
        )
        # Associate the new local user account with the OAuth token
        oauth.user = user
        # Save and commit our database models
        db.session.add_all([user, oauth])
        db.session.commit()
        # Log in the new local user account
        login_user(user)
        flash("Successfully signed in with Twitter.")
        """

        # If user account already exists but there is no associated OAuth token
        if current_user.is_authenticated:
            oauth.user = current_user
            db.session.add(oauth)
            db.session.commit()
            flash("Successfully linked Twitter account.")
        else:
            # Create a new local user account for this user
            user = User(
                first_name=twitter_username,
                # Less secure, but no username is generated, so on its own password cannot be used to log in
                password='password'
            )
            # Associate the new local user account with the OAuth token
            oauth.user = user
            # Save and commit our database models
            db.session.add_all([user, oauth])
            db.session.commit()
            # Log in the new local user account
            login_user(user)
            flash("Successfully signed in with Twitter.")

    # Disable Flask-Dance's default behavior for saving the OAuth token
    return False


# Authentication


@users_blueprint.route('/signup', methods=["GET", "POST"])
@not_loggedin_required
def signup():
    form = UserForm(request.form)
    if request.method == "POST" and form.validate():
        try:
            new_user = User(form.data['first_name'], form.data['last_name'],
                            form.data['username'], form.data['password'])
            db.session.add(new_user)
            db.session.commit()
            # Log user in after registration
            login_user(new_user)
        except IntegrityError as e:
            flash("Username already taken")
            return render_template('users/signup.html', form=form)
        flash('User Created!')
        return redirect(url_for('users.users'))
    return render_template('users/signup.html', form=form)


@users_blueprint.route('/login', methods=["GET", "POST"])
@not_loggedin_required
def login():
    form = LoginForm(request.form)
    if request.method == "POST":
        if form.validate():
            user = User.authenticate(
                form.data['username'], form.data['password'])
            if user:
                login_user(user)
                flash("You are now logged in!")
                return redirect(url_for('users.users'))
        flash("Invalid Credentials")
    return render_template('users/login.html', form=form)


@users_blueprint.route('/logout')
@login_required
def logout():
    logout_user()
    flash('Logged Out!')
    return redirect(url_for('users.login'))


# Views


@users_blueprint.route('/', methods=["GET", "POST"])
def users():
    return render_template('users/index.html', users=User.query.all())


@users_blueprint.route('/<int:id>', methods=["GET", "PATCH", "DELETE"])
@login_required
@current_user_required
def show(id):
    selected_user = User.query.get(id)
    # Use b"PATCH" because Flask Modus makes request.method a bytes literal
    if request.method == b"PATCH":
        user_form = UserForm(request.form)
        if user_form.validate():
            selected_user.first_name = request.form['first_name']
            selected_user.last_name = request.form['last_name']
            selected_user.username = request.form['username']
            selected_user.password = bcrypt.generate_password_hash(
                request.form['password']).decode('UTF-8')
            db.session.add(selected_user)
            db.session.commit()
            flash("User Updated!")
            return redirect(url_for('users.users'))
        else:
            flash("Form Error: User Not Updated")
            return render_template('users/edit.html', user=selected_user, user_form=user_form, delete_form=DeleteForm())
    if request.method == b"DELETE":
        delete_form = DeleteForm(request.form)
        if delete_form.validate():
            db.session.delete(selected_user)
            db.session.commit()
            flash("User Deleted!")
            return redirect(url_for('users.users'))
        else:
            flash("Form Error: User Not Deleted")
            return redirect(url_for('users.users'))
    return render_template('users/show.html', user=selected_user)


@users_blueprint.route('/<int:id>/edit', methods=["GET"])
@login_required
@current_user_required
def edit(id):
    selected_user = User.query.get(id)
    user_form = UserForm(obj=selected_user)
    return render_template('users/edit.html', user=selected_user, user_form=user_form, delete_form=DeleteForm())

Unit 2/07-auth-and-oauth/05-oauth/Solution/project/users/templates/users/edit.html
{% extends "base.html" %}
{% block content %}

<a href="{{ url_for('users.users') }}">User Directory</a>

<form action="{{ url_for('users.show', id=user.id) }}?_method=PATCH" method="POST">
  {{ user_form.hidden_tag() }}
  {% for field in user_form if field.widget.input_type != 'hidden' %}
  <p>
    {{ field.label }}
    {{ field }}
    <span>
      {% if field.errors %}
        {% for error in field.errors %}
          {{ error }}
        {% endfor %}
      {% endif %}
    </span>
  </p>
  {% endfor %}
  <input type="submit" value="Edit user">
</form>

<form action="{{ url_for('users.show', id=user.id) }}?_method=DELETE" method="POST">
  {{ delete_form.hidden_tag() }}
  <input type="submit" value="Delete user">
</form>

<h2>Twitter Login</h2>
<a href="{{ url_for('twitter.login') }}">Link your Twitter account</a>

{% endblock %}

Unit 2/07-auth-and-oauth/05-oauth/Solution/project/users/templates/users/index.html
{% extends "base.html" %}
{% block content %}

<a href="{{ url_for('users.users') }}">User Directory</a>

{% for user in users %}
  <p>{{ user.first_name }} {{ user.last_name if user.last_name != None }} | ID: {{ user.id }}</p>
{% endfor %}

{% endblock %}

Unit 2/07-auth-and-oauth/05-oauth/Solution/project/users/templates/users/login.html
{% extends 'base.html' %}

{% block content %}

<a href="{{ url_for('users.users') }}">User Directory</a>

<h2>Login</h2>

<form method="POST" action="{{url_for('users.login')}}">
  {{ form.csrf_token }}
  {% for field in form if field.widget.input_type != 'hidden' %}
  <p>
    {{ field.label }}
    {{ field }}
    <span>
      {% if field.errors %}
        {% for error in field.errors %}
          {{ error }}
        {% endfor %}
      {% endif %}
    </span>
  </p>
  {% endfor %}
  <input type="submit" value="Log In!">
</form>

<h2>Twitter Login</h2>
<a href="{{ url_for('twitter.login') }}">Link your Twitter account</a>

{% endblock %}

Unit 2/07-auth-and-oauth/05-oauth/Solution/project/users/templates/users/show.html
{% extends "base.html" %}
{% block content %}

<a href="{{ url_for('users.users') }}">User Directory</a>

<h2>{{ user.first_name }} {{ user.last_name if user.last_name != None }}</h2>

<p>ID: {{ user.id }}</p>

{% endblock %}

Unit 2/07-auth-and-oauth/05-oauth/Solution/project/users/templates/users/signup.html
{% extends 'base.html' %}

{% block content %}

<a href="{{ url_for('users.users') }}">User Directory</a>

<form method="POST" action="{{url_for('users.signup')}}">
  {{ form.csrf_token }}
  {% for field in form if field.widget.input_type != 'hidden' %}
  <p>
    {{ field.label }}
    {{ field }}
    <span>
      {% if field.errors %}
        {% for error in field.errors %}
          {{ error }}
        {% endfor %}
      {% endif %}
    </span>
  </p>
  {% endfor %}
  <input type="submit" value="Sign Up!">
</form>

{% endblock %}