Unit 2/06-larger-applications/01-blueprints/Solution/solution/messages/models.py
from solution import db


class Message(db.Model):

    __tablename__ = "messages"

    id = db.Column(db.Integer, primary_key=True)
    content = db.Column(db.String(100))
    user_id = db.Column(db.Integer, db.ForeignKey('users.id'))

    def __init__(self, content, user_id):
        self.content = content
        self.user_id = user_id

    # Set a custom string representation of message objects
    def __repr__(self):
        return f"User {self.user_id} wrote '{self.content}'"

Unit 2/06-larger-applications/01-blueprints/Solution/solution/users/models.py
from solution import db


class User(db.Model):

    __tablename__ = "users"

    # Columns in table
    id = db.Column(db.Integer, primary_key=True)
    # 50 characters is a sensible default for the max length of first/last names
    first_name = db.Column(db.String(50))
    last_name = db.Column(db.String(50))
    messages = db.relationship('Message', backref='user', lazy='dynamic')

    def __init__(self, first_name, last_name):
        self.first_name = first_name
        self.last_name = last_name

    # Set a custom string representation of user objects
    def __repr__(self):
        return f"User {self.first_name} {self.last_name}"

Unit 2/06-larger-applications/01-blueprints/Solution/solution/messages/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, validators


class MessageForm(FlaskForm):
    content = StringField(
        'Content', [validators.DataRequired(), validators.Length(min=1, max=100)])


class DeleteForm(FlaskForm):
    pass

Unit 2/06-larger-applications/01-blueprints/Solution/solution/__init__.py
# Flask and extensions
from flask import Flask, redirect
from flask_sqlalchemy import SQLAlchemy
from flask_modus import Modus
from flask_migrate import Migrate

# Create instance of Flask class
app = Flask(__name__)

# Configure Flask Modus
modus = Modus(app)

# Configure SQLAlchemy
app.config['SQLALCHEMY_DATABASE_URI'] = 'postgres://localhost/users-messages'
app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False
db = SQLAlchemy(app)

# Configure WTForms
# For production set secret key in env variable: os.environ.get('SECRET_KEY')
app.config['SECRET_KEY'] = "this_is_an_insecure_development_key"

# Import blueprints here to avoid circular imports
from solution.users.views import users_blueprint
from solution.messages.views import messages_blueprint

# Register blueprints
app.register_blueprint(users_blueprint, url_prefix='/users')
app.register_blueprint(
    messages_blueprint, url_prefix='/users/<int:user_id>/messages')


@app.route('/', methods=["GET"])
def home():
    return redirect('users')

Unit 2/06-larger-applications/01-blueprints/Solution/solution/messages/views.py
from flask import Blueprint, render_template, url_for, request, redirect, flash

from solution import db
from solution.messages.forms import MessageForm, DeleteForm
from solution.users.models import User
from solution.messages.models import Message

messages_blueprint = Blueprint(
    'messages', __name__, template_folder='templates')


# See all messages for user
@messages_blueprint.route('/', methods=["GET", "POST"])
def messages(user_id):
    if request.method == "POST":
        form = MessageForm(request.form)
        if form.validate():
            new_message = Message(request.form["content"], user_id)
            db.session.add(new_message)
            db.session.commit()
            flash("Message Created!")
        else:
            flash("Form Error: Message Not Created")
            return render_template('messages/new.html', user=User.query.get(user_id), form=form)
    return render_template('messages/index.html', user=User.query.get(user_id))


@messages_blueprint.route('/new', methods=["GET"])
def new_message(user_id):
    form = MessageForm()
    return render_template('messages/new.html', user=User.query.get(user_id), form=form)


@messages_blueprint.route('/<int:id>', methods=["GET", "PATCH", "DELETE"])
def show_message(user_id, id):
    selected_message = Message.query.get(id)
    # Use b"PATCH" because Flask Modus makes request.method a bytes literal
    if request.method == b"PATCH":
        message_form = MessageForm(request.form)
        if message_form.validate():
            selected_message.content = request.form['content']
            db.session.add(selected_message)
            db.session.commit()
            flash("Message Updated!")
            return redirect(url_for('messages.messages', user_id=user_id))
        else:
            flash("Form Error: Message Not Updated")
            return render_template('messages/edit.html', user=User.query.get(user_id), message=selected_message, message_form=message_form, delete_form=DeleteForm())
    if request.method == b"DELETE":
        delete_form = DeleteForm(request.form)
        if delete_form.validate():
            db.session.delete(selected_message)
            db.session.commit()
            flash("Message Deleted!")
            return redirect(url_for('messages.messages', user_id=user_id))
        else:
            flash("Form Error: Message Not Deleted")
            return redirect(url_for('messages.messages', user_id=user_id))
    return render_template('messages/show.html', user=User.query.get(user_id), message=selected_message)


@messages_blueprint.route('/<int:id>/edit', methods=["GET"])
def edit_message(user_id, id):
    selected_message = Message.query.get(id)
    message_form = MessageForm(obj=selected_message)
    return render_template('messages/edit.html', user=User.query.get(user_id), message=selected_message, message_form=message_form, delete_form=DeleteForm())

Unit 2/06-larger-applications/01-blueprints/Solution/solution/users/views.py
from flask import Blueprint, render_template, url_for, request, redirect, flash

from solution import db
from solution.users.forms import UserForm, DeleteForm
from solution.users.models import User

users_blueprint = Blueprint('users', __name__, template_folder='templates')


@users_blueprint.route('/', methods=["GET", "POST"])
def users():
    if request.method == "POST":
        form = UserForm(request.form)
        if form.validate():
            new_user = User(request.form["first_name"],
                            request.form["last_name"])
            db.session.add(new_user)
            db.session.commit()
            flash("User Created!")
        else:
            flash("Form Error: User Not Created")
            return render_template('users/new.html', form=form)
    return render_template('users/index.html', users=User.query.all())


@users_blueprint.route('/new', methods=["GET"])
def new():
    form = UserForm()
    return render_template('users/new.html', form=form)


@users_blueprint.route('/<int:id>', methods=["GET", "PATCH", "DELETE"])
def show(id):
    selected_user = User.query.get(id)
    # Use b"PATCH" because Flask Modus makes request.method a bytes literal
    if request.method == b"PATCH":
        user_form = UserForm(request.form)
        if user_form.validate():
            selected_user.first_name = request.form['first_name']
            selected_user.last_name = request.form['last_name']
            db.session.add(selected_user)
            db.session.commit()
            flash("User Updated!")
            return redirect(url_for('users.users'))
        else:
            flash("Form Error: User Not Updated")
            return render_template('users/edit.html', user=selected_user, user_form=user_form, delete_form=DeleteForm())
    if request.method == b"DELETE":
        delete_form = DeleteForm(request.form)
        if delete_form.validate():
            db.session.delete(selected_user)
            db.session.commit()
            flash("User Deleted!")
            return redirect(url_for('users.users'))
        else:
            flash("Form Error: User Not Deleted")
            return redirect(url_for('users.users'))
    return render_template('users/show.html', user=selected_user)


@users_blueprint.route('/<int:id>/edit', methods=["GET"])
def edit(id):
    selected_user = User.query.get(id)
    user_form = UserForm(obj=selected_user)
    return render_template('users/edit.html', user=selected_user, user_form=user_form, delete_form=DeleteForm())

Unit 2/06-larger-applications/01-blueprints/Solution/solution/messages/templates/messages/edit.html
{% extends "base.html" %}
{% block content %}

<a href="{{ url_for('messages.messages', user_id=user.id) }}">User Messages</a>

<br><br>
<form action="{{ url_for('messages.show_message', user_id=user.id, id=message.id) }}?_method=PATCH" method="POST">
  {{ message_form.hidden_tag() }}
  {% for field in message_form if field.widget.input_type != 'hidden' %}
  <p>
    {{ field.label }}
    {{ field }}
    <span>
      {% if field.errors %}
        {% for error in field.errors %}
          {{ error }}
        {% endfor %}
      {% endif %}
    </span>
  </p>
  {% endfor %}
  <input type="submit" value="Edit message">
</form>

<form action="{{ url_for('messages.show_message', user_id=user.id, id=message.id) }}?_method=DELETE" method="POST">
  {{ delete_form.hidden_tag() }}
  <input type="submit" value="Delete message">
</form>

{% endblock %}

Unit 2/06-larger-applications/01-blueprints/Solution/solution/messages/templates/messages/new.html
{% extends "base.html" %}
{% block content %}

<h2>{{ user.first_name }} {{ user.last_name }}</h2>

<form action={{ url_for('messages.messages', user_id=user.id) }} method="POST">
  {{ form.hidden_tag() }}
  
  {% for field in form if field.widget.input_type != 'hidden' %}
  <p>
    {{ field.label }}
    {{ field }}
    <span>
      {% if field.errors %}
        {% for error in field.errors %}
          {{ error }}
        {% endfor %}
      {% endif %}
    </span>
  </p>
  {% endfor %}
  <input type="submit" value="Create a message">
</form>

{% endblock %}

Unit 2/06-larger-applications/01-blueprints/Solution/solution/users/templates/users/edit.html
{% extends "base.html" %}
{% block content %}

<a href="{{ url_for('users.users') }}">User Directory</a>
<!-- <a href="{#url_for('show', snack=snack.id)#}">View this snack</a> -->
<br><br>

<form action="{{ url_for('users.show', id=user.id) }}?_method=PATCH" method="POST">
  {{ user_form.hidden_tag() }}
  {% for field in user_form if field.widget.input_type != 'hidden' %}
  <p>
    {{ field.label }}
    {{ field }}
    <span>
      {% if field.errors %}
        {% for error in field.errors %}
          {{ error }}
        {% endfor %}
      {% endif %}
    </span>
  </p>
  {% endfor %}
  <input type="submit" value="Edit user">
</form>

<form action="{{ url_for('users.show', id=user.id) }}?_method=DELETE" method="POST">
  {{ delete_form.hidden_tag() }}
  <input type="submit" value="Delete user">
</form>

{% endblock %}

Unit 2/06-larger-applications/01-blueprints/Solution/solution/users/templates/users/new.html
{% extends "base.html" %}
{% block content %}

<form action={{ url_for('users.users') }} method="POST">
  {{ form.hidden_tag() }}
  
  {% for field in form if field.widget.input_type != 'hidden' %}
  <p>
    {{ field.label }}
    {{ field }}
    <span>
      {% if field.errors %}
        {% for error in field.errors %}
          {{ error }}
        {% endfor %}
      {% endif %}
    </span>
  </p>
  {% endfor %}
  <button type="submit">Add a user</button>
</form>

{% endblock %}