Unit 2/07-auth-and-oauth/05-oauth/Solution/project/tags/models.py
from project import db


class Tag(db.Model):

    __tablename__ = "tags"

    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(100))

    def __init__(self, name):
        self.name = name

    # Set a custom string representation of message objects
    def __repr__(self):
        return f"Tag {self.name}"

Unit 2/07-auth-and-oauth/05-oauth/Solution/project/tags/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, validators, SelectMultipleField, widgets
from project.messages.models import Message


class MultiCheckboxField(SelectMultipleField):
    widget = widgets.ListWidget(prefix_label=False)
    option_widget = widgets.CheckboxInput()


class TagForm(FlaskForm):
    name = StringField(
        'Name', [validators.DataRequired(), validators.Length(min=1, max=100)])

    messages = MultiCheckboxField(
        'Messages',
        coerce=int)

    def set_choices(self):
        self.messages.choices = [(m.id, m.content)
                                 for m in Message.query.all()]


class DeleteForm(FlaskForm):
    pass

Unit 2/07-auth-and-oauth/05-oauth/Solution/project/tags/views.py
from flask import Blueprint, render_template, url_for, request, redirect, flash

from project import db
from project.tags.forms import TagForm, DeleteForm
from project.tags.models import Tag

tags_blueprint = Blueprint('tags', __name__, template_folder='templates')


@tags_blueprint.route('/', methods=["GET", "POST"])
def tags():
    if request.method == "POST":
        form = TagForm(request.form)
        if form.validate():
            new_tag = Tag(request.form["name"])
            db.session.add(new_tag)
            db.session.commit()
            flash("Tag Created!")
        else:
            flash("Form Error: Tag Not Created")
            return render_template('tags/new.html', form=form)
    return render_template('tags/index.html', tags=Tag.query.all())


@tags_blueprint.route('/new', methods=["GET"])
def new():
    form = TagForm()
    form.set_choices()
    return render_template('tags/new.html', form=form)


@tags_blueprint.route('/<int:id>', methods=["GET", "PATCH", "DELETE"])
def show(id):
    selected_tag = Tag.query.get(id)
    # Use b"PATCH" because Flask Modus makes request.method a bytes literal
    if request.method == b"PATCH":
        tag_form = TagForm(request.form)
        if tag_form.validate():
            selected_tag.name = request.form['name']
            db.session.add(selected_tag)
            db.session.commit()
            flash("Tag Updated!")
            return redirect(url_for('tags.tags'))
        else:
            flash("Form Error: Tag Not Updated")
            return render_template('tags/edit.html', tag=selected_tag, tag_form=tag_form, delete_form=DeleteForm())
    if request.method == b"DELETE":
        delete_form = DeleteForm(request.form)
        if delete_form.validate():
            db.session.delete(selected_tag)
            db.session.commit()
            flash("Tag Deleted!")
            return redirect(url_for('tags.tags'))
        else:
            flash("Form Error: Tag Not Deleted")
            return redirect(url_for('tags.tags'))
    return render_template('tags/show.html', tag=selected_tag)


@tags_blueprint.route('/<int:id>/edit', methods=["GET"])
def edit(id):
    selected_tag = Tag.query.get(id)
    tag_form = TagForm(obj=selected_tag)
    tag_form.set_choices()
    return render_template('tags/edit.html', tag=selected_tag, tag_form=tag_form, delete_form=DeleteForm())

Unit 2/07-auth-and-oauth/05-oauth/Solution/project/tags/templates/tags/edit.html
{% extends "base.html" %}
{% block content %}

<a href="{{ url_for('tags.tags') }}">Tag Directory</a>

<form action="{{ url_for('tags.show', id=tag.id) }}?_method=PATCH" method="POST">
  {{ tag_form.hidden_tag() }}
  {% for field in tag_form if field.widget.input_type != 'hidden' %}
  <p>
    {{ field.label }}
    {{ field }}
    <span>
      {% if field.errors %}
        {% for error in field.errors %}
          {{ error }}
        {% endfor %}
      {% endif %}
    </span>
  </p>
  {% endfor %}
  <input type="submit" value="Edit tag">
</form>

<form action="{{ url_for('tags.show', id=tag.id) }}?_method=DELETE" method="POST">
  {{ delete_form.hidden_tag() }}
  <input type="submit" value="Delete tag">
</form>

{% endblock %}

Unit 2/07-auth-and-oauth/05-oauth/Solution/project/tags/templates/tags/index.html
{% extends "base.html" %}
{% block content %}

<a href="{{ url_for('tags.tags') }}">Tag Directory</a>

{% for tag in tags %}
  <p>{{ tag.name }} | ID: {{ tag.id }}</p>
  <ul>
  {% for message in tag.messages %}
    <li>{{ message.content }}</li>
  {% endfor %}
  </ul>
{% endfor %}

{% endblock %}

Unit 2/07-auth-and-oauth/05-oauth/Solution/project/tags/templates/tags/new.html
{% extends "base.html" %}
{% block content %}

<a href="{{ url_for('tags.tags') }}">Tag Directory</a>

<form action={{ url_for('tags.tags') }} method="POST">
  {{ form.hidden_tag() }}
  
  {% for field in form if field.widget.input_type != 'hidden' %}
  <p>
    {{ field.label }}
    {{ field }}
    <span>
      {% if field.errors %}
        {% for error in field.errors %}
          {{ error }}
        {% endfor %}
      {% endif %}
    </span>
  </p>
  {% endfor %}
  <button type="submit">Add a tag</button>
</form>

{% endblock %}

Unit 2/07-auth-and-oauth/05-oauth/Solution/project/tags/templates/tags/show.html
{% extends "base.html" %}
{% block content %}

<a href="{{ url_for('tags.tags') }}">Tag Directory</a>

<h2>{{ tag.name }}</h2>

<p>ID: {{ tag.id }}</p>

{% endblock %}